[package]
name = "telera-layout"
version = "0.5.0"
edition = "2024"

[dependencies]
csscolorparser = { version = "0.7.0", features = [ "named-colors" ] }
serial_test = "3.2.0"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.19"

[features]
parse_logger = []
